services:
  postgres:
    container_name: mapshare
    image: postgres
    env_file:
         - .ENV
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PGOPTIONS: "-c max_connections=1000"

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres"]
    ulimits:
      nofile:
        soft: 10000
        hard: 20000


  mapshare-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
         - .ENV
    ports:
      - "3010:3010"
    volumes:
      - .:/server
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3010
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
    ulimits:
      nofile:
        soft: 10000
        hard: 20000

volumes:
  db_data: