services:
  postgres:
    container_name: mapshare
    image: postgres
    env_file:
         - .ENV
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  

  mapshare-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
         - .ENV
    ports:
      - "3010:3010"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3010
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres

volumes:
  db_data: